#!/usr/bin/env python

import rospy
import numpy as np
from std_msgs.msg import String
from std_msgs.msg import UInt16
from std_msgs.msg import Bool
from sensor_msgs.msg import Imu
from bluerov_ros_playground.msg import Attitude


ATTITUDE = [0]*6
heading = 2.88 
PI = np.pi
KP = 100
KD = 10

rospy.init_node('heading_controller', anonymous=True)
#pub_rc4 = rospy.Publisher('/BlueRov2/rc_channel4/set_pwm', UInt16, queue_size=10)
#pub_arm = rospy.Publisher('/BlueRov2/arm', Bool, queue_size=10)
pub_pwm = rospy.Publisher('/Command/heading', UInt16, queue_size=10)
rate = rospy.Rate(4)


def sawtooth(x):
	return (x+PI)%(2*PI)-PI

def callback_att(msg):
	global ATTITUDE
	ATTITUDE = [msg.roll,
		    msg.pitch,
		    msg.yaw,
		    msg.rollspeed,
		    msg.pitchspeed,
		    msg.yawspeed]

def control(yaw, yawspeed):
	return KP*sawtooth(yaw-heading) + KD*yawspeed
	
def saturation(pwm, pwm_max):
	pwm_min = 1500 - (pwm_max-1500)
	if pwm > pwm_max :
		pwm = pwm_max
	if pwm < pwm_min:
		pwm = pwm_min
	return int(pwm)



while not rospy.is_shutdown():
	#pub_arm.publish(1)
	rospy.Subscriber('/BlueRov2/imu/attitude', Attitude, callback_att)
        yaw = ATTITUDE[2]
	yawspeed = ATTITUDE[5]
	u = control(yaw, yawspeed)
	pwm = 1500-u
        pwm = saturation(pwm, 1550)

        print(u,pwm,yaw)
	#pub_rc4.publish(pwm)
	pub_pwm.publish(pwm)
	rate.sleep()



