#!/usr/bin/env python

import rospy
from bluerov_ros_playground.msg import Set_depth
from bluerov_ros_playground.msg import Set_heading
from bluerov_ros_playground.msg import Set_velocity


def set_msg_depth(depth_desired, pwm_max, pwm_neutral, K, KI, KP, KD, rosrate):
	msg_depth = Set_depth()
	msg_depth.depth_desired = depth_desired
	msg_depth.pwm_max = pwm_max
	msg_depth.pwm_neutral = pwm_neutral
	msg_depth.K = K
	msg_depth.KI= KI
	msg_depth.KP= KP
	msg_depth.KD= KD
	msg_depth.rosrate = rosrate
	return msg_depth

def set_msg_heading(heading_desired, KP, KD, pwm_max, pwm_neutral, rosrate):
	msg_heading = Set_heading()
	msg_heading.heading_desired = heading_desired
	msg_heading.KP = KP
	msg_heading.KD = KD
	msg_heading.pwm_max = pwm_max
	msg_heading.pwm_neutral = pwm_neutral
	msg_heading.rosrate = rosrate
	return msg_heading

def set_msg_velocity(velocity_desired, KP, KD, pwm_max, pwm_neutral, rosrate):
	msg_velocity = Set_velocity()
	msg_velocity.velocity_desired = velocity_desired
	msg_velocity.KP = KP
	msg_velocity.KD = KD
	msg_velocity.pwm_max = pwm_max
	msg_velocity.pwm_neutral = pwm_neutral
	msg_velocity.rosrate = rosrate
	return msg_velocity


if __name__ == "__main__":
	rospy.init_node('Setter', anonymous=True)
	rate = rospy.Rate(4)
	pub_depth = rospy.Publisher('/Settings/set_depth', Set_depth, queue_size=10)
	pub_heading = rospy.Publisher('/Settings/set_heading', Set_heading, queue_size=10)
	pub_velocity = rospy.Publisher('/Settings/set_velocity', Set_velocity, queue_size=10)
	msg_depth = set_msg_depth(-0.2, 1650, 1500, 0,    100, 600, 50,       4)
	msg_heading = set_msg_heading(2.96, 35, 25, 1550, 1500, 4)
	msg_velocity = set_msg_velocity(1., 100, 25, 1550, 1500, 4)

	while not rospy.is_shutdown():
		pub_depth.publish(msg_depth)
		pub_heading.publish(msg_heading)
		pub_velocity.publish(msg_velocity)
		rate.sleep()
