#!/usr/bin/env python

import rospy
from std_msgs.msg import UInt16
from std_msgs.msg import Bool

pwm_depth, pwm_heading = 0, 0

rospy.init_node('commander', anonymous=True)
pub_rc3 = rospy.Publisher('/BlueRov2/rc_channel3/set_pwm', UInt16, queue_size=10)
pub_rc4 = rospy.Publisher('/BlueRov2/rc_channel4/set_pwm', UInt16, queue_size=10)
pub_rc5 = rospy.Publisher('/BlueRov2/rc_channel5/set_pwm', UInt16, queue_size=10)
pub_arm = rospy.Publisher('/BlueRov2/arm', Bool, queue_size=10)
rate = rospy.Rate(4)


def callback_depth(msg):
	global pwm_depth
	pwm_depth = msg.data

def callback_heading(msg):
	global pwm_heading
	pwm_heading = msg.data

#def callback_joy(msg):
#	global JOY
#	JOY = []




while not rospy.is_shutdown():
	pub_arm.publish(1)
	rospy.Subscriber('/Command/depth', UInt16, callback_depth)
	rospy.Subscriber('/Command/heading', UInt16, callback_heading)
	#rospy.Subscriber('/Command/joy', Joy, callback_joy)
	pub_rc3.publish(pwm_depth)
	if abs(pwm_heading-1500)>25:  # Correct the heading
		pub_rc4.publish(pwm_heading)
	else:
		pub_rc5.publish(1550) # Goes forward
	rate.sleep()



