#!/usr/bin/env python

import rospy
from std_msgs.msg import String
from std_msgs.msg import UInt16
from std_msgs.msg import Bool
from sensor_msgs.msg import Imu
from bluerov_ros_playground.msg import Bar30

#axis z goes up

g = 9.81  # m.s^-2 gravitationnal acceleration 
p0 = 990*100 #Pa surface pressure NEED to be cheked
rho = 1000 # kg.m^3  water density
K = 500 #for the proportionnal controller
DEPTH_DESIRED = -0.20
mesured_pressure = [0]*4

rospy.init_node('depth_controller', anonymous=True)
pub_rc3 = rospy.Publisher('/BlueRov2/rc_channel3/set_pwm', UInt16, queue_size=10)
pub_arm = rospy.Publisher('/BlueRov2/arm', Bool, queue_size=10)
rate = rospy.Rate(4)
logs_depthControl = open("logs_depthControl.txt", 'a')

def callback_imu(msg):
	imu_data= [ msg.orientation.x,
                 msg.orientation.y,
                 msg.orientation.z,
	         msg.orientation.w ]
	print(imu_data)

def callback_bar30(msg):
	global mesured_pressure
	mesured_pressure = [ msg.time_boot_ms,
        	 msg.press_abs,
        	 msg.press_diff,
        	 msg.temperature ]

def control(p):
	depth  = -(p-p0)/(rho*g)
        print("Real Depth :",depth  )
	u = K*(DEPTH_DESIRED-depth)
        logs_depthControl.write("depth : \n".format( depth ))
	return u
	
def saturation(pwm, pwm_max):
	pwm_min = 1500 - (pwm_max-1500)
	if pwm > pwm_max :
		pwm = pwm_max
	if pwm < pwm_min:
		pwm = pwm_min
	return int(pwm)

while not rospy.is_shutdown():
	pub_arm.publish(1)
	rospy.Subscriber('/BlueRov2/bar30', Bar30, callback_bar30)
        logs_depthControl.write("mesured_pressure :{} \n".format(mesured_pressure[1]))
        p = mesured_pressure[1]*100
	u = control(p)
	pwm = 1500+u
        logs_depthControl.write("pwm  :{} \n".format(pwm))
        print(mesured_pressure[1],pwm) 
        pwm = saturation(pwm, 1650)
	pub_rc3.publish(pwm)
	rate.sleep()



